/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jturner' at '11/29/16 7:25 PM' with Gradle 2.14.1
 *
 * @author jturner, @date 11/29/16 7:25 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
